In [3]:
import pandas as pd 
import numpy as np

In [4]:
merged = pd.read_csv('inputs/merged.csv')
merged.describe()

,Year,SP500_Return,Percent_Change_in_GDP,CPI,Construction_Unemployment_Rate,Manufacturing_Unemployment_Rate,Finance_Unemployment_Rate
count,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000
mean,2013.500000,0.019360,1.988889,234.864106,9.511111,5.663889,3.484722
std,5.224536,0.083256,6.020003,24.654914,5.178519,2.703431,1.602872
min,2005.000000,-0.224100,-29.900000,192.366667,3.500000,2.500000,1.200000
25%,2009.000000,-0.011650,0.925000,216.656917,5.700000,3.900000,2.275000
50%,2013.500000,0.032450,2.350000,234.758833,7.700000,4.650000,2.950000
75%,2018.000000,0.062175,3.300000,250.930833,12.150000,7.025000,4.325000
max,2022.000000,0.241100,35.300000,298.525000,25.500000,12.600000,7.300000